theme: jekyll-theme-cayman
title: Souhila Gamal |  Data Analyst📊📈
description: Data Analytics Portfolio | Featuring the end-to-end case studies, SQL scripts, python analysis ,interactive Tableau dashboards and business insights
