theme: jekyll-theme-cayman
title: Souhila Gamal |  Data Analyst📊📈 Portfolio featuring the end to end the case studies SQL scripts, python analysis ,interactive Tableau dashboards and business insights
description: Data Analytics Portfolio | Featuring the end-to-end case studies, SQL scripts, python analysis ,interactive Tableau dashboards and business insights
